flowchart LR
  subgraph Console["Console (Angular)"]
    A[Simulador\nEscolhe Canal/IA] -->|POST texto| P(Config-API)
    CRUD[CRUD Configs] --> CfgAPI(Config-API)
  end

  %% Roteamento por engine no Predict-API
  P -->|IA=spacy-IA| S1[/Predictor spaCy/]
  P -->|IA=stick-IA| S2[/Predictor Stick-IA/]
  P --> M[(MongoDB)]

  %% Config e dados de treino
  CfgAPI <--> M[(MongoDB)]
  CfgAPI -->|enqueue train| TrReq[[Kafka: train.requests]]

  %% Trainers
  TrReq --> TW1(Trainer spaCy)
  TrReq --> TW2(Trainer Stick-IA\nTF-IDF+RandomForest)

  TW1 --> MinIO[(MinIO: modelos)]
  TW2 --> MinIO
  TW1 --> M
  TW2 --> M

  %% Predição -> consulta meta no Mongo e baixa artefato no MinIO
  S1 -->|read meta/version| M
  S2 -->|read meta/version| M
  S1 -->|load model| MinIO
  S2 -->|load model| MinIO

  %% Observabilidade
  Obs[(Prometheus/Grafana)] -. metrics/logs .-> P
  Obs -. metrics/logs .-> CfgAPI
  Obs -. metrics/logs .-> TW1
  Obs -. metrics/logs .-> TW2
