server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/nlp}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

predict:
  base-url: ${PREDICT_API_BASE_URL:http://localhost:8000}
j-assistant:
  base-url: ${J_ASSISTANT_API_BASE_URL:http://j-assistant-predict-api:8001}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
topics:
  trainRequests: train.requests
  trainStatus: train.status

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: config-api

resilience4j:
  circuitbreaker:
    instances:
      predictService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 3                # últimas 2 chamadas
        minimum-number-of-calls: 10
        failure-rate-threshold: 50             # abre se >= 50% falhar
        slow-call-duration-threshold: 10s       # chamadas lentas contam como falha lenta
        slow-call-rate-threshold: 50
        wait-duration-in-open-state: 30       # quanto tempo fica aberto
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
        ignore-exceptions: