REQUESTS_TOPIC_DEFAULT = "train.requests"
STATUS_TOPIC_DEFAULT = "train.status"
WORKER_GROUP_ID = "trainer-worker"

SCOPE_SUBJECT = "subject"
SCOPE_CHANNEL = "channel"
SCOPE_BOTH = "both"

MODEL_SCOPE_SUBJECT = "subject"
MODEL_SCOPE_CHANNEL = "channel"

STATUS_RUNNING = "RUNNING"
STATUS_SUCCESS = "SUCCESS"
STATUS_FAILED  = "FAILED"

READY = "READY"
TRAINING = "TRAINING"
FAILED = "FAILED"
